### ISSUE TITLE
When i place amalgamator it crashes my game :(

### ISSUE THREAD

**Issue by TomThatHatesModCrash** [TeamBR-Modding/ModernAlchemy#34]
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 4/10/15 5:09 PM
Description: Unexpected error

java.lang.RuntimeException: Failed to create TE with class class com.dyonovan.modernalchemy.common.tileentity.machines.TileAmalgamator
    at openmods.block.OpenBlock.createTileEntity(OpenBlock.java:147)
    at openmods.block.OpenBlock.createTileEntity(OpenBlock.java:123)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660)
    at net.minecraft.world.World.func_147465_d(World.java:451)
    at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:206)
    at openmods.item.ItemOpenBlock.func_77648_a(ItemOpenBlock.java:64)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1436)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1942)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: Tried to register invalid slot: 1 (inventory size: 1)
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
    at openmods.utils.SidedInventoryAdapter.registerSlot(SidedInventoryAdapter.java:50)
    at openmods.utils.SidedInventoryAdapter.registerSlot(SidedInventoryAdapter.java:45)
    at com.dyonovan.modernalchemy.common.tileentity.machines.TileAmalgamator.<init>(TileAmalgamator.java:91)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at openmods.block.OpenBlock.createTileEntity(OpenBlock.java:145)
    ... 19 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at openmods.block.OpenBlock.createTileEntity(OpenBlock.java:147)
    at openmods.block.OpenBlock.createTileEntity(OpenBlock.java:123)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660)
    at net.minecraft.world.World.func_147465_d(World.java:451)
    at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:206)
    at openmods.item.ItemOpenBlock.func_77648_a(ItemOpenBlock.java:64)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1436)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Drag0nDem0n'/4, l='MpServer', x=237.50, y=5.62, z=-922.50]]
    Chunk stats: MultiplayerChunkCache: 599, 599
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (232,4,-928), Chunk: (at 8,0,0 in 14,-58; contains blocks 224,0,-928 to 239,255,-913), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
    Level time: 233 game time, 233 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 7 total; [EntitySlime['Slime'/16416, l='MpServer', x=199.72, y=4.00, z=-982.65], EntitySlime['Slime'/23171, l='MpServer', x=191.97, y=5.00, z=-983.47], EntitySlime['Slime'/17428, l='MpServer', x=238.41, y=4.00, z=-882.10], EntitySlime['Slime'/48852, l='MpServer', x=210.59, y=4.83, z=-995.51], EntitySlime['Slime'/31270, l='MpServer', x=194.66, y=4.00, z=-993.34], EntityClientPlayerMP['Drag0nDem0n'/4, l='MpServer', x=237.50, y=5.62, z=-922.50], EntitySlime['Slime'/74792, l='MpServer', x=207.50, y=4.00, z=-1000.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 155079728 bytes (147 MB) / 316047360 bytes (301 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1236 Minecraft Forge 10.13.2.1236 8 mods loaded, 8 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1236} [Forge Mod Loader](forge-1.7.10-10.13.2.1236.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1236} [Minecraft Forge](forge-1.7.10-10.13.2.1236.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsCore{0.6} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.0B9} [CoFH Core](CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-328.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    modernalchemy{Beta-1.1} [Modern Alchemy](ModernAlchemy-1.7.10-Beta-1.1-B1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8
    Launched Version: 1.7.10-Forge10.13.2.1236
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.3308, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Dyonovan** [comment]
make sure you are using the latest snapshot of openmodslib
http://www.openmods.info:8080/

**Comment by TomThatHatesModCrash** [comment]
i am using

**Comment by TomThatHatesModCrash** [comment]
i like i downloaded from skydaz .com modern alchemy mod

**Comment by TomThatHatesModCrash** [comment]
its a installer

**Comment by Dyonovan** [comment]
I would be very careful about getting mods anywhere but minecraft forums or curse. Try getting modern alchemy from http://www.curse.com/mc-mods/minecraft/228359-modern-alchemy.

**Comment by TomThatHatesModCrash** [comment]
where i can get that CoFHCore?

**Comment by TomThatHatesModCrash** [comment]
wait wait do you got like skype? so i can like show you everything.
